### PR TITLE
LL-319

### PR DESCRIPTION
**Pull request by KevinLemon112**
# Description

In this new PR/Ticket, HTTP protocols have been added (GET, POST, DELETE) for the ActiveMQ notification service. These new services connect to the MongoDB database to enable viewing, creating, and deleting Luminosity users. Postman was used in order to check POST and DELETE functionality. GET can be checked from the port browser or Postman as well. 

***Note: If using GitHub Codespaces, make sure your port is public before testing (for me, it was port 4000). Also, be sure to run "npm install" in both the publish and subscribe folders and also in the src/notification directory to ensure all dependencies are installed correctly.***

***Note 2: When using Postman, be sure to change the type of request to whatever you are trying to do. It will be GET by default***

Subsequent # (issue): LL-319

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- [GET] go to src/notification directory and run "docker compose up --build". Then use Postman/browser to check GET functionality: enter browser/port url + "/publish/accounts/all" at the end of the URL for all accounts or "/publish/accounts/:id" at the end of the URL for a specific account via ID (replace ":id" with actual MongoDB account ID). Enter this in either Postman or in browser URL.

- [POST] go to src/notification directory and run "docker compose up --build". Then use Postman to check POST functionality: enter browser/port url + "/publish/accounts/new" at the end of the URL + click Body/raw (make sure it is labeled as JSON) and input a JSON in this format:

{
  "creationDate": "2023-08-28T05:33:57.702Z",
  "deletionDate": "2023-08-29T05:33:57.702Z",   <- optional, you can not include this if you want as well
  "lastUpdated": "2023-08-30T05:33:57.702Z",
  "email": "example@example.com",
  "name": "John Doe",
  "devicesLinked": []
}

OR (if you want to test linking a device)

{
  "email": "example@example.com",
  "name": "John Doe",
  "creationDate": "2023-08-28T05:33:57.702Z",
  "deletionDate": "2023-08-29T05:33:57.702Z",   <- optional, you can not include this if you want as well
  "lastUpdated": "2023-08-30T05:33:57.702Z",
  "devicesLinked": [
    {
      "uuid": "device1_uuid",
      "lastUpdated": "2023-08-28T05:33:57.702Z",
      "powered": true,   <- optional, you can not include this if you want as well
      "poweredTimestamp": "2023-08-28T05:33:57.702Z",   <- optional, you can not include this if you want as well
      "connected": true,   <- optional, you can not include this if you want as well
      "connectedTimestamp": "2023-08-28T05:33:57.702Z",   <- optional, you can not include this if you want as well
      "color": "#FFFFFF",   <- optional, you can not include this if you want as well
      "colorTimestamp": "2023-08-28T05:33:57.702Z",   <- optional, you can not include this if you want as well
      "brightness": 50,   <- optional, you can not include this if you want as well
      "brightnessTimestamp": "2023-08-28T05:33:57.702Z"   <- optional, you can not include this if you want as well
    }
  ]
}

and click send. Check on MongoDB to verify user has been created.

- [DELETE] go to src/notification directory and run "docker compose up --build". Then use Postman to check DELETE functionality: enter browser/port url + "/publish/accounts/:id/delete" at the end of the URL for a specific account via ID (replace ":id" with actual MongoDB account ID) and click send. Check on MongoDB to verify user has been deleted.

# Checklist (when relevant):

- [x] My code follows the style guidelines of this project

[TypeScript](https://google.github.io/styleguide/tsguide.html)
[Python](https://peps.python.org/pep-0008/)
[Schema](https://learn.microsoft.com/en-us/previous-versions/windows/desktop/forefront-2010/ee652242(v=vs.100))
- [x] I have included a reviewer on the pull request [@pogi7], [@erikajledesma], and [@vliu36]
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by pogi7** [comment]
@KevinLemon112 You'll need to DM the .env file to me @vliu36 & @erikajledesma

**Comment by pogi7** [comment]
@KevinLemon112 I'm getting the following error after running `npm i` and `docker compose up --build` in a Github Codespace.

```bash
subscribe-service  | /root/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:859
subscribe-service  |     return new TSError(diagnosticText, diagnosticCodes, diagnostics);
subscribe-service  |            ^
subscribe-service  | TSError: ⨯ Unable to compile TypeScript:
subscribe-service  | subscribe.ts(1,21): error TS2307: Cannot find module 'express' or its corresponding type declarations.
subscribe-service  | subscribe.ts(2,34): error TS2307: Cannot find module 'mqtt' or its corresponding type declarations.
subscribe-service  | subscribe.ts(3,30): error TS2307: Cannot find module 'uuid' or its corresponding type declarations.
subscribe-service  | subscribe.ts(4,44): error TS2307: Cannot find module 'mongoose' or its corresponding type declarations.
subscribe-service  | subscribe.ts(5,20): error TS2307: Cannot find module 'dotenv' or its corresponding type declarations.
subscribe-service  | subscribe.ts(24,29): error TS7006: Parameter 'receivedTopic' implicitly has an 'any' type.
subscribe-service  | subscribe.ts(24,44): error TS7006: Parameter 'msg' implicitly has an 'any' type.
subscribe-service  | 
subscribe-service  |     at createTSError (/root/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:859:12)
subscribe-service  |     at reportTSError (/root/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:863:19)
subscribe-service  |     at getOutput (/root/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1077:36)
subscribe-service  |     at Object.compile (/root/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1433:41)
subscribe-service  |     at Module.m._compile (/root/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1617:30)
subscribe-service  |     at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
subscribe-service  |     at Object.require.extensions.<computed> [as .ts] (/root/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1621:12)
subscribe-service  |     at Module.load (node:internal/modules/cjs/loader:1197:32)
subscribe-service  |     at Function.Module._load (node:internal/modules/cjs/loader:1013:12)
subscribe-service  |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12) {
subscribe-service  |   diagnosticCodes: [
subscribe-service  |     2307, 2307,
subscribe-service  |     2307, 2307,
subscribe-service  |     2307, 7006,
subscribe-service  |     7006
subscribe-service  |   ]
subscribe-service  | }
activemq           |  INFO | No Spring WebApplicationInitializer types detected on classpath
publish-service    | /root/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:859
publish-service    |     return new TSError(diagnosticText, diagnosticCodes, diagnostics);
publish-service    |            ^
publish-service    | TSError: ⨯ Unable to compile TypeScript:
publish-service    | publish.ts(1,21): error TS2307: Cannot find module 'express' or its corresponding type declarations.
publish-service    | publish.ts(2,34): error TS2307: Cannot find module 'mqtt' or its corresponding type declarations.
publish-service    | publish.ts(3,30): error TS2307: Cannot find module 'uuid' or its corresponding type declarations.
publish-service    | publish.ts(4,60): error TS2307: Cannot find module 'mongoose' or its corresponding type declarations.
publish-service    | publish.ts(5,20): error TS2307: Cannot find module 'dotenv' or its corresponding type declarations.
publish-service    | publish.ts(43,46): error TS7006: Parameter '_req' implicitly has an 'any' type.
publish-service    | publish.ts(43,52): error TS7006: Parameter 'res' implicitly has an 'any' type.
publish-service    | publish.ts(53,46): error TS7006: Parameter 'req' implicitly has an 'any' type.
publish-service    | publish.ts(53,51): error TS7006: Parameter 'res' implicitly has an 'any' type.
publish-service    | publish.ts(74,47): error TS7006: Parameter 'req' implicitly has an 'any' type.
publish-service    | publish.ts(74,52): error TS7006: Parameter 'res' implicitly has an 'any' type.
publish-service    | publish.ts(91,56): error TS7006: Parameter 'req' implicitly has an 'any' type.
publish-service    | publish.ts(91,61): error TS7006: Parameter 'res' implicitly has an 'any' type.
publish-service    | publish.ts(111,37): error TS7006: Parameter 'req' implicitly has an 'any' type.
publish-service    | publish.ts(111,42): error TS7006: Parameter 'res' implicitly has an 'any' type.
publish-service    | publish.ts(121,57): error TS7006: Parameter 'err' implicitly has an 'any' type.
publish-service    | publish.ts(132,25): error TS7006: Parameter 'error' implicitly has an 'any' type.
publish-service    | publish.ts(142,9): error TS7006: Parameter 'error' implicitly has an 'any' type.
publish-service    | 
publish-service    |     at createTSError (/root/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:859:12)
publish-service    |     at reportTSError (/root/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:863:19)
publish-service    |     at getOutput (/root/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1077:36)
publish-service    |     at Object.compile (/root/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1433:41)
publish-service    |     at Module.m._compile (/root/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1617:30)
publish-service    |     at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
publish-service    |     at Object.require.extensions.<computed> [as .ts] (/root/.npm/_npx/1bf7c3c15bf47d04/node_modules/ts-node/src/index.ts:1621:12)
publish-service    |     at Module.load (node:internal/modules/cjs/loader:1197:32)
publish-service    |     at Function.Module._load (node:internal/modules/cjs/loader:1013:12)
publish-service    |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12) {
publish-service    |   diagnosticCodes: [
publish-service    |     2307, 2307, 2307, 2307,
publish-service    |     2307, 7006, 7006, 7006,
publish-service    |     7006, 7006, 7006, 7006,
publish-service    |     7006, 7006, 7006, 7006,
publish-service    |     7006, 7006
publish-service    |   ]
publish-service    | }
subscribe-service exited with code 1
publish-service exited with code 1
```

**Review by pogi7 — CHANGES_REQUESTED** [review]
@KevinLemon112 
The code in the Dockerfiles in the publish and subscribe files should only be copying the source files and running `npm i` to get the dependencies needed.

Change
```bash
COPY . ./
```

to 
```bash
npm i 
COPY . ./
```

**Review by erikajledesma — COMMENTED** [review]
@KevinLemon112 I can run a GET request but get the following error when I try to POST:
```
publish-service    | MongoServerError: Document failed validation
publish-service    |     at InsertOneOperation.execute (/app/node_modules/mongodb/src/operations/insert.ts:79:13)
publish-service    |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
publish-service    |     at async executeOperationAsync (/app/node_modules/mongodb/src/operations/execute_operation.ts:190:12) {
publish-service    |   index: 0,
publish-service    |   code: 121,
publish-service    |   errInfo: {
publish-service    |     failingDocumentId: new ObjectId('65ed5a3172d48cc400e962eb'),
publish-service    |     details: {
publish-service    |       operatorName: '$jsonSchema',
publish-service    |       title: 'accounts',
publish-service    |       schemaRulesNotSatisfied: [Array]
publish-service    |     }
publish-service    |   },
publish-service    |   [Symbol(errorLabels)]: Set(0) {}
publish-service    | }

**Review by pogi7 — APPROVED** [review]
lgtm!  works with linked devices as well.  please make sure that this info is documented in Confluence somewhere

**Review by erikajledesma — APPROVED** [review]
lgtm, also tested linked devices. nice job Kevin!!

**Pull request merged**
